import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CLIPS, FPS, HEIGHT, MAX_SECONDS, TITLE_CARD, WIDTH, type Clip } from './clips';
import { NARRATION } from './narration';

/**
 * `pnpm video:render`
 *
 * Turns the captured clips into the two deliverables, using FFmpeg only. No
 * frame is generated by a model, and no number on screen comes from anywhere
 * but the running application.
 *
 * The pipeline is deliberately boring: normalise every clip to identical
 * parameters, draw the cards, overlay the three callouts, concatenate, then
 * burn captions for the second cut. Every step is a separate file on disk, so a
 * bad step can be inspected rather than guessed at.
 */

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const RAW = path.join(ROOT, 'output', 'raw');
const WORK = path.join(ROOT, 'output', 'work');
const OUT = path.join(ROOT, 'output');
const SILENT = path.join(OUT, 'stateproof-walkthrough-silent.mp4');
const CAPTIONED = path.join(OUT, 'stateproof-walkthrough-captioned.mp4');
const SRT = path.join(ROOT, 'captions.srt');
const CUES = path.join(OUT, 'cue-sheet.json');

/** StateProof's own palette, so the cards belong to the same product. */
const BG = '0x08090C';
const INK = '0xE8EDF5';
const DIM = '0x97A2B4';
const ACCENT = '0x4DA3FF';
const FAIL = '0xFF6B6B';

function ffmpeg(args: string[]): void {
  execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args], {
    stdio: ['ignore', 'pipe', 'pipe'],
    maxBuffer: 64 * 1024 * 1024,
  });
}

function probeSeconds(file: string): number {
  const out = execFileSync(
    'ffprobe',
    ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file],
    { encoding: 'utf8' },
  );
  return Number.parseFloat(out.trim());
}

/**
 * A font FFmpeg can actually load.
 *
 * `drawtext` needs a file on Windows; fontconfig name lookup is not dependable
 * across builds. The first readable candidate wins, and the path is escaped the
 * way the filter parser expects.
 */
function fontFile(): string {
  const candidates = [
    'C:/Windows/Fonts/segoeui.ttf',
    'C:/Windows/Fonts/arial.ttf',
    '/System/Library/Fonts/Supplemental/Arial.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
  ];
  const found = candidates.find((candidate) => existsSync(candidate));
  if (found === undefined) {
    throw new Error(`no usable font found; tried:\n  ${candidates.join('\n  ')}`);
  }
  return found.replace(/\\/g, '/').replace(/:/g, '\\:');
}

const FONT = fontFile();

function esc(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/:/g, '\\:').replace(/'/g, "\\'");
}

function drawText(
  text: string,
  options: { size: number; colour: string; y: string; from?: number; to?: number },
): string {
  const enable =
    options.from === undefined ? '' : `:enable='between(t,${String(options.from)},${String(options.to ?? 9999)})'`;
  return (
    `drawtext=fontfile='${FONT}':text='${esc(text)}':fontcolor=${options.colour}` +
    `:fontsize=${String(options.size)}:x=(w-text_w)/2:y=${options.y}${enable}`
  );
}

/** A card: solid ground, centred type, a short fade at each end. */
function renderCard(
  file: string,
  seconds: number,
  lines: Array<{ text: string; size: number; colour: string; y: string }>,
): void {
  const filters = [
    ...lines.map((line) => drawText(line.text, { size: line.size, colour: line.colour, y: line.y })),
    `fade=t=in:st=0:d=0.4`,
    `fade=t=out:st=${(seconds - 0.4).toFixed(2)}:d=0.4`,
    'format=yuv420p',
  ].join(',');

  ffmpeg([
    '-f', 'lavfi',
    '-i', `color=c=${BG}:s=${String(WIDTH)}x${String(HEIGHT)}:r=${String(FPS)}:d=${seconds.toFixed(2)}`,
    '-vf', filters,
    '-c:v', 'libx264', '-preset', 'medium', '-crf', '18', '-pix_fmt', 'yuv420p',
    '-r', String(FPS),
    file,
  ]);
}

/**
 * The three callouts the brief asks for, placed over the clip they belong to.
 *
 * They are restrained on purpose: a translucent band and one line of text, held
 * long enough to read. No arrows, no zooms — the figure is already on screen,
 * the callout only says which one to look at.
 */
interface Callout {
  readonly text: string;
  readonly colour: string;
  readonly from: number;
  readonly to: number;
}

const CALLOUTS: Record<string, Callout[]> = {
  'demo-findings': [
    { text: 'required 40.00 USD   ·   executed 55.00 USD', colour: FAIL, from: 8, to: 20 },
  ],
  'demo-timeline': [
    { text: 'refund executed at seq 8   ·   approval at seq 12', colour: FAIL, from: 7, to: 19 },
  ],
  comparison: [
    { text: 'baseline 12 calls   ·   first deployment 3   ·   every repeat 0', colour: ACCENT, from: 14, to: 29 },
  ],
};

function calloutFilters(clipId: string): string[] {
  const callouts = CALLOUTS[clipId] ?? [];
  return callouts.flatMap((callout) => [
    `drawbox=x=0:y=h-172:w=iw:h=104:color=black@0.72:t=fill:enable='between(t,${String(callout.from)},${String(callout.to)})'`,
    `drawbox=x=0:y=h-172:w=iw:h=3:color=${callout.colour}@0.9:t=fill:enable='between(t,${String(callout.from)},${String(callout.to)})'`,
    drawText(callout.text, { size: 40, colour: callout.colour, y: 'h-138', from: callout.from, to: callout.to }),
  ]);
}

/**
 * Normalise a captured clip.
 *
 * Playwright's webm is variable frame rate and its exact size can drift by a
 * pixel; concatenation needs every input identical. `fps` resamples, `scale` and
 * `pad` guarantee the frame, and the clip is trimmed to its planned length so
 * the cue sheet and the picture agree.
 */
function normaliseClip(clip: Clip, source: string, target: string, offset: number): number {
  const available = probeSeconds(source);
  const duration = Math.min(clip.seconds, Math.max(2, available - offset - 0.15));
  const filters = [
    `fps=${String(FPS)}`,
    `scale=${String(WIDTH)}:${String(HEIGHT)}:force_original_aspect_ratio=decrease`,
    `pad=${String(WIDTH)}:${String(HEIGHT)}:(ow-iw)/2:(oh-ih)/2:color=${BG}`,
    'setsar=1',
    ...calloutFilters(clip.id),
    'fade=t=in:st=0:d=0.3',
    `fade=t=out:st=${(duration - 0.3).toFixed(2)}:d=0.3`,
    'format=yuv420p',
  ].join(',');

  ffmpeg([
    // Seek past the navigation and the content wait, which Playwright recorded
    // because it starts filming when the page is created.
    '-ss', offset.toFixed(2),
    '-i', source,
    '-t', duration.toFixed(2),
    '-vf', filters,
    '-c:v', 'libx264', '-preset', 'medium', '-crf', '20', '-pix_fmt', 'yuv420p',
    '-r', String(FPS), '-an',
    target,
  ]);
  return probeSeconds(target);
}

interface Segment {
  readonly id: string;
  readonly kind: 'title' | 'card' | 'clip';
  readonly file: string;
  readonly seconds: number;
}

function timecode(seconds: number): string {
  const ms = Math.round(seconds * 1000);
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  const s = Math.floor((ms % 60_000) / 1000);
  const milli = ms % 1000;
  const pad = (value: number, width = 2): string => String(value).padStart(width, '0');
  return `${pad(h)}:${pad(m)}:${pad(s)},${pad(milli, 3)}`;
}

/**
 * Captions built from measured segment durations.
 *
 * Lines for a segment share that segment's window, split in proportion to their
 * length, so a caption never runs past the picture it belongs to.
 */
function writeCaptions(segments: Segment[]): number {
  const starts = new Map<string, { start: number; seconds: number }>();
  let cursor = 0;
  for (const segment of segments) {
    if (segment.kind !== 'card') {
      const key = segment.kind === 'title' ? 'title' : segment.id;
      const existing = starts.get(key);
      if (existing === undefined) starts.set(key, { start: cursor, seconds: segment.seconds });
      else existing.seconds += segment.seconds;
    }
    cursor += segment.seconds;
  }

  const blocks: string[] = [];
  let index = 1;
  for (const [key, window] of starts) {
    const lines = NARRATION.filter((line) => line.at === key);
    if (lines.length === 0) continue;
    const weights = lines.map((line) => line.text.length);
    const total = weights.reduce((sum, weight) => sum + weight, 0);
    // Breathing room at each end so speech never butts against a cut.
    const usable = Math.max(1, window.seconds - 0.8);
    let offset = window.start + 0.4;
    lines.forEach((line, position) => {
      const share = (weights[position] ?? 1) / total;
      const length = Math.max(1.4, usable * share);
      blocks.push(
        `${String(index)}\n${timecode(offset)} --> ${timecode(Math.min(offset + length, window.start + window.seconds - 0.1))}\n${line.text}\n`,
      );
      index += 1;
      offset += length;
    });
  }
  writeFileSync(SRT, `${blocks.join('\n')}`, 'utf8');
  return index - 1;
}

function concat(segments: Segment[], target: string): void {
  const listFile = path.join(WORK, 'concat.txt');
  writeFileSync(
    listFile,
    segments.map((segment) => `file '${segment.file.replace(/\\/g, '/')}'`).join('\n') + '\n',
    'utf8',
  );
  // Every input already shares codec, size, rate and pixel format, so the
  // streams copy rather than re-encode: no generation loss at the joins.
  ffmpeg(['-f', 'concat', '-safe', '0', '-i', listFile, '-c', 'copy', '-movflags', '+faststart', target]);
}

/**
 * `pnpm video:render -- --only demo-setup`
 *
 * Renders one clip on its own, with exactly the treatment it gets inside the
 * film — same size, rate, codec, fades and callouts — so it drops onto an
 * editing timeline as a replacement for that section.
 */
function renderSingle(id: string, offsets: Map<string, number>): void {
  const clip = CLIPS.find((candidate) => candidate.id === id);
  if (clip === undefined) {
    throw new Error(`no clip named "${id}". Known: ${CLIPS.map((entry) => entry.id).join(', ')}`);
  }
  const source = path.join(RAW, `${clip.id}.webm`);
  if (!existsSync(source)) {
    throw new Error(`no capture for ${clip.id}; run: pnpm video:capture -- --only ${clip.id}`);
  }

  const clipsDir = path.join(OUT, 'clips');
  mkdirSync(clipsDir, { recursive: true });

  const target = path.join(clipsDir, `stateproof-${clip.id}.mp4`);
  const seconds = normaliseClip(clip, source, target, offsets.get(clip.id) ?? 0);

  process.stdout.write(
    [
      '',
      `clip:     ${clip.id}`,
      `purpose:  ${clip.purpose}`,
      `file:     ${path.relative(ROOT, target)}`,
      `duration: ${seconds.toFixed(2)}s (planned ${String(clip.seconds)}s)`,
      `format:   ${String(WIDTH)}x${String(HEIGHT)} · ${String(FPS)} fps · H.264 · yuv420p`,
      '',
      'RESULT: CLIP RENDERED',
      '',
    ].join('\n'),
  );
}

function main(): void {
  if (!existsSync(RAW)) {
    throw new Error('no captured clips; run `pnpm video:capture` first');
  }
  /*
   * Where each clip's performance actually begins.
   *
   * Playwright starts recording when the page is created, so navigation and the
   * wait for content are in the file too. The capture measures that and the
   * seek skips it, instead of the render trimming from the top and keeping the
   * loading state.
   */
  const manifestPath = path.join(RAW, 'capture-manifest.json');
  const offsets = new Map<string, number>();
  if (existsSync(manifestPath)) {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
      results?: Array<{ id: string; offset?: number }>;
    };
    for (const row of manifest.results ?? []) offsets.set(row.id, row.offset ?? 0);
  }

  const argv = process.argv.slice(2);
  const onlyIndex = argv.indexOf('--only');
  if (onlyIndex !== -1) {
    const id = argv[onlyIndex + 1];
    if (id === undefined) throw new Error('--only needs a clip id');
    renderSingle(id, offsets);
    return;
  }

  rmSync(WORK, { recursive: true, force: true });
  mkdirSync(WORK, { recursive: true });
  mkdirSync(OUT, { recursive: true });

  const segments: Segment[] = [];

  process.stdout.write('cards\n');
  const titleFile = path.join(WORK, '000-title.mp4');
  renderCard(titleFile, TITLE_CARD.seconds, [
    { text: TITLE_CARD.title, size: 132, colour: INK, y: 'h/2-170' },
    { text: TITLE_CARD.subtitle, size: 54, colour: DIM, y: 'h/2-10' },
    { text: TITLE_CARD.byline, size: 30, colour: DIM, y: 'h/2+120' },
  ]);
  segments.push({ id: 'title', kind: 'title', file: titleFile, seconds: probeSeconds(titleFile) });
  process.stdout.write(`  ok    title card\n`);

  let order = 1;
  const missing: string[] = [];
  for (const clip of CLIPS) {
    if (clip.card !== undefined) {
      const file = path.join(WORK, `${String(order).padStart(3, '0')}-card-${clip.id}.mp4`);
      renderCard(file, clip.card.seconds, [
        { text: clip.card.title, size: 76, colour: INK, y: clip.card.subtitle === undefined ? 'h/2-38' : 'h/2-70' },
        ...(clip.card.subtitle === undefined
          ? []
          : [{ text: clip.card.subtitle, size: 36, colour: DIM, y: 'h/2+30' }]),
      ]);
      segments.push({ id: `${clip.id}-card`, kind: 'card', file, seconds: probeSeconds(file) });
      order += 1;
    }

    const source = path.join(RAW, `${clip.id}.webm`);
    if (!existsSync(source)) {
      missing.push(clip.id);
      process.stdout.write(`  MISS  ${clip.id} — no capture\n`);
      continue;
    }
    const target = path.join(WORK, `${String(order).padStart(3, '0')}-${clip.id}.mp4`);
    const seconds = normaliseClip(clip, source, target, offsets.get(clip.id) ?? 0);
    segments.push({ id: clip.id, kind: 'clip', file: target, seconds });
    process.stdout.write(`  ok    ${clip.id.padEnd(16)} ${seconds.toFixed(1)}s\n`);
    order += 1;
  }

  if (missing.length > 0) {
    throw new Error(
      `missing captures: ${missing.join(', ')}\n` +
        `re-shoot with: pnpm video:capture -- --only ${missing.join(',')}`,
    );
  }

  const total = segments.reduce((sum, segment) => sum + segment.seconds, 0);
  process.stdout.write(`\ntotal ${Math.floor(total / 60)}m ${(total % 60).toFixed(0)}s\n`);
  if (total > MAX_SECONDS) {
    throw new Error(
      `the cut is ${total.toFixed(1)}s, over the ${String(MAX_SECONDS)}s ceiling. ` +
        'Shorten clip durations in video/src/clips.ts and re-render.',
    );
  }

  process.stdout.write('\nconcatenating\n');
  concat(segments, SILENT);
  process.stdout.write(`  ok    ${path.relative(ROOT, SILENT)}\n`);

  const captionCount = writeCaptions(segments);
  process.stdout.write(`  ok    ${path.relative(ROOT, SRT)} (${String(captionCount)} cues)\n`);

  process.stdout.write('\nburning captions\n');
  const subtitlePath = SRT.replace(/\\/g, '/').replace(/:/g, '\\:');
  ffmpeg([
    '-i', SILENT,
    '-vf',
    `subtitles='${subtitlePath}':force_style='FontName=Segoe UI,FontSize=22,PrimaryColour=&H00F5EDE8,` +
      `OutlineColour=&H00000000,BorderStyle=3,Outline=2,Shadow=0,MarginV=52,Alignment=2'`,
    '-c:v', 'libx264', '-preset', 'medium', '-crf', '20', '-pix_fmt', 'yuv420p',
    '-r', String(FPS), '-movflags', '+faststart',
    CAPTIONED,
  ]);
  process.stdout.write(`  ok    ${path.relative(ROOT, CAPTIONED)}\n`);

  writeFileSync(
    CUES,
    `${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        totalSeconds: Number(total.toFixed(2)),
        maxSeconds: MAX_SECONDS,
        width: WIDTH,
        height: HEIGHT,
        fps: FPS,
        segments: segments.map((segment) => ({
          id: segment.id,
          kind: segment.kind,
          seconds: Number(segment.seconds.toFixed(2)),
        })),
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
  process.stdout.write(`  ok    ${path.relative(ROOT, CUES)}\n`);
  process.stdout.write('\nRESULT: RENDERED\n');
}

try {
  main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? (error.stack ?? error.message) : String(error)}\n`);
  process.exitCode = 1;
}

